"""Add user table

Revision ID: 719fb2c52f69
Revises: 
Create Date: 2019-02-19 20:18:50.483919

"""
from alembic import op
import sqlalchemy as sa
from core import app
from core.models.user import User as UserModel

# revision identifiers, used by Alembic.
revision = '719fb2c52f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=32), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('created', sa.TIMESTAMP(),
                  server_default=sa.text('CURRENT_TIMESTAMP'),
                  nullable=False),
        sa.Column('updated', sa.TIMESTAMP(),
                  server_default=sa.text(
                      'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###

    # insert users
    user = UserModel()
    username = app.config['AUTH_USERNAME']
    password = app.config['AUTH_PASSWORD']
    user.hash_password(password)
    hash_password = user.password_hash



    op.bulk_insert(
        user_table,
        [
            {'username': username, 'password_hash': hash_password}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
